package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

type AcquiaOneShotList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items           []AcquiaOneShot `json:"items"`
}

type AcquiaOneShot struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata"`
	Spec              AcquiaOneShotSpec   `json:"spec"`
	Status            AcquiaOneShotStatus `json:"status,omitempty"`
}

type AcquiaOneShotSpec struct {
	Site        string                       `json:"site"`
	Environment string                       `json:"environment"`
	Database    string                       `json:"database"`
	Image       string                       `json:"image"`
	Credentials AcquiaOneShotSpecCredentials `json:"credentials"`
}

type AcquiaOneShotSpecCredentials struct {
	Acquia string `json:"acquia"`
	Docker string `json:"docker"`
}

type Phase string

const (
	PhaseRunning  Phase = "Running"
	PhaseComplete Phase = "Complete"
	PhaseFailed   Phase = "Failed"
)

type AcquiaOneShotStatus struct {
	Job   string `json:"job,omitempty"`
	Phase Phase  `json:"phase,omitempty"`
	Error string `json:"error,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaOneShot) DeepCopyInto(out *AcquiaOneShot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaOneShot.
func (in *AcquiaOneShot) DeepCopy() *AcquiaOneShot {
	if in == nil {
		return nil
	}
	out := new(AcquiaOneShot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcquiaOneShot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaOneShotList) DeepCopyInto(out *AcquiaOneShotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcquiaOneShot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaOneShotList.
func (in *AcquiaOneShotList) DeepCopy() *AcquiaOneShotList {
	if in == nil {
		return nil
	}
	out := new(AcquiaOneShotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcquiaOneShotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaOneShotSpec) DeepCopyInto(out *AcquiaOneShotSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaOneShotSpec.
func (in *AcquiaOneShotSpec) DeepCopy() *AcquiaOneShotSpec {
	if in == nil {
		return nil
	}
	out := new(AcquiaOneShotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaOneShotStatus) DeepCopyInto(out *AcquiaOneShotStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaOneShotStatus.
func (in *AcquiaOneShotStatus) DeepCopy() *AcquiaOneShotStatus {
	if in == nil {
		return nil
	}
	out := new(AcquiaOneShotStatus)
	in.DeepCopyInto(out)
	return out
}
