package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaSnapshotScheduled) DeepCopyInto(out *AcquiaSnapshotScheduled) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaSnapshotScheduled.
func (in *AcquiaSnapshotScheduled) DeepCopy() *AcquiaSnapshotScheduled {
	if in == nil {
		return nil
	}
	out := new(AcquiaSnapshotScheduled)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcquiaSnapshotScheduled) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}

	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaSnapshotScheduledList) DeepCopyInto(out *AcquiaSnapshotScheduledList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcquiaSnapshotScheduled, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaSnapshotScheduledList.
func (in *AcquiaSnapshotScheduledList) DeepCopy() *AcquiaSnapshotScheduledList {
	if in == nil {
		return nil
	}
	out := new(AcquiaSnapshotScheduledList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcquiaSnapshotScheduledList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}

	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaSnapshotScheduledSpec) DeepCopyInto(out *AcquiaSnapshotScheduledSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaSnapshotScheduledSpec.
func (in *AcquiaSnapshotScheduledSpec) DeepCopy() *AcquiaSnapshotScheduledSpec {
	if in == nil {
		return nil
	}
	out := new(AcquiaSnapshotScheduledSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaSnapshot) DeepCopyInto(out *AcquiaSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaSnapshot.
func (in *AcquiaSnapshot) DeepCopy() *AcquiaSnapshot {
	if in == nil {
		return nil
	}
	out := new(AcquiaSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcquiaSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}

	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaSnapshotList) DeepCopyInto(out *AcquiaSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AcquiaSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaSnapshotList.
func (in *AcquiaSnapshotList) DeepCopy() *AcquiaSnapshotList {
	if in == nil {
		return nil
	}
	out := new(AcquiaSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AcquiaSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}

	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaSnapshotSpec) DeepCopyInto(out *AcquiaSnapshotSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaSnapshotSpec.
func (in *AcquiaSnapshotSpec) DeepCopy() *AcquiaSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(AcquiaSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcquiaStatus) DeepCopyInto(out *AcquiaStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcquiaStatus.
func (in *AcquiaStatus) DeepCopy() *AcquiaStatus {
	if in == nil {
		return nil
	}
	out := new(AcquiaStatus)
	in.DeepCopyInto(out)
	return out
}
