apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: mtk.skpr.io/v1alpha1
kind: AcquiaSnapshot
metadata:
  name: dev
  namespace: demo
spec:
  database:
    site: "prod:example"
    environment: dev
    name: example
  credentials: dev-acquia-creds
  docker:
    image: previousnext/exampe-db:dev-latest
  config:
    sanitize:
      tables:
        - name: users
          fields:
            - name: mail
              value: "SANITIZED_MAIL"
            - name: pass
              value: "SANITIZED_PASSWORD"
    nodata:
      - cache*
      - webform_submission
      - webform_submission_data
      - webform_submission_log
      - captcha_sessions
      - history
      - flood
      - batch
      - queue
      - sessions
      - semaphore
      - search_api_task
      - search_dataset
      - search_index
      - search_total
    ignore:
      - __ACQUIA_MONITORING__
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-acquia-creds
  namespace: demo
type: Opaque
stringData:
  acquia.username: "xxxxxxxxxxxxxxxxxx"
  acquia.password: "xxxxxxxxxxxxxxxxxx"
